# Generated by Django 3.2.7 on 2022-02-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='wings/%y')),
                ('udate', models.CharField(max_length=100)),
                ('disc', models.TextField()),
            ],
        ),
    ]
