# Generated by Django 3.2.7 on 2022-05-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0002_videos_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='pics')),
                ('disc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='videos',
            name='course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='cvs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
